clone:
  lfs: true

definitions:
  steps:
    - step: &build-macos
        runs-on:
          - 'self.hosted'
          - 'macos'
        name: 'Build for macOS'
        script:
          - git submodule update --recursive --init
          - brew install pkg-config
          - python3 -m pip install pygit2
          - python3 -u build.py --path-to-build build-macos --build-number $BITBUCKET_BUILD_NUMBER
        artifacts:
          - build-macos
    - step: &build-windows
        runs-on:
          - 'self.hosted'
          - 'windows'
        name: 'Build for Windows'
        script:
          - git submodule update --recursive --init
          - python -m pip install pygit2
          - python -u build.py --path-to-build build-windows --build-number "$env:BITBUCKET_BUILD_NUMBER"
        artifacts:
          - build-windows
    - step: &build-dist
        runs-on:
          - 'self.hosted'
          - 'macos'
        name: 'Build distribution package'
        script:
          - git submodule update --recursive --init
          - python3 -m pip install pygit2
          - python3 -u scripts/dist.py --path-to-build build-dist --build-number $BITBUCKET_BUILD_NUMBER
        artifacts:
          - build-dist/*.zip
        depends-on:
          - build-macos
          - build-windows

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *build-macos
        - step: *build-windows
      - step: *build-dist
  tags:
    'v*':
      - parallel:
        - step: *build-macos
        - step: *build-windows
      - step: *build-dist
  branches:
    main:
      - parallel:
        - step: *build-macos
        - step: *build-windows
      - step: *build-dist
  custom:
    macos:
      - step: *build-macos
    windows:
      - step: *build-windows
    dist:
      - parallel:
        - step: *build-macos
        - step: *build-windows
      - step: *build-dist
